export const browserCoreExamples = [
  "haoclaw browser status",
  "haoclaw browser start",
  "haoclaw browser stop",
  "haoclaw browser tabs",
  "haoclaw browser open https://example.com",
  "haoclaw browser focus abcd1234",
  "haoclaw browser close abcd1234",
  "haoclaw browser screenshot",
  "haoclaw browser screenshot --full-page",
  "haoclaw browser screenshot --ref 12",
  "haoclaw browser snapshot",
  "haoclaw browser snapshot --format aria --limit 200",
  "haoclaw browser snapshot --efficient",
  "haoclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "haoclaw browser navigate https://example.com",
  "haoclaw browser resize 1280 720",
  "haoclaw browser click 12 --double",
  'haoclaw browser type 23 "hello" --submit',
  "haoclaw browser press Enter",
  "haoclaw browser hover 44",
  "haoclaw browser drag 10 11",
  "haoclaw browser select 9 OptionA OptionB",
  "haoclaw browser upload /tmp/haoclaw/uploads/file.pdf",
  'haoclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "haoclaw browser dialog --accept",
  'haoclaw browser wait --text "Done"',
  "haoclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "haoclaw browser console --level error",
  "haoclaw browser pdf",
];
